# Generated by Django 4.2.5 on 2023-09-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Кличка')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('tel', models.CharField(max_length=13, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Собака', 'Собака'), ('Кошка', 'Кошка'), ('Бобер', 'Бобер')], max_length=20, verbose_name='Вид питомца')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=20, verbose_name='Специалист')),
                ('fname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('experience', models.IntegerField(verbose_name='Стаж врачевания')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo', models.FloatField(verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('summary', models.TextField(max_length=500, verbose_name='Описание')),
                ('onwer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.owner', verbose_name='Хозяин')),
                ('type_of_animal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.type_of_animal', verbose_name='Тип животного')),
                ('veterinarian', models.ManyToManyField(to='catalog.veterinarian', verbose_name='Ветеринар - специалист')),
            ],
        ),
    ]
