# Generated by Django 4.2.5 on 2023-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_kino_image_alter_actor_born_alter_actor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='summary',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
